# Generated by Django 3.2.13 on 2022-11-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_prefergenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefergenre',
            old_name='tvmovi',
            new_name='tvmovie',
        ),
    ]
