# Generated by Django 3.2.13 on 2022-11-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
    ]
