# Generated by Django 3.2.13 on 2022-11-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_prefer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='prefer_user',
        ),
    ]
