# Generated by Django 3.2.13 on 2022-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_genre_prefer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefer',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
