# Generated by Django 3.2.13 on 2022-11-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_prefer_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prefer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='prefer',
            constraint=models.UniqueConstraint(fields=('user', 'genre'), name='user_prefer_value'),
        ),
    ]
