# Generated by Django 3.2.13 on 2022-12-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='self_introduce',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
